apiVersion: v1
kind: ConfigMap
metadata:
  name: common-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common-service.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*"
    }

