apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-variables # rename or not
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common-service.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.serviceEnvs | nindent 2 }}